### ISSUE TITLE
Wrong test case on unrestricted function returning linear bool?

### ISSUE THREAD

**Issue by jjant** [mdko/attapl#1]
Hey @mdko. I was just going through ATAPL and found your repo super useful.

I found this test case while checking my implementation and I believe it is incorrect:
https://github.com/mdko/attapl/blob/7346b389b60d032d20c71807bd4d5b010c5b877a/linlam/test/Spec.hs#L115-L117

I think returning a linear value from an unrestricted function is fine in this case, because it's allocating a new one each time. I believe these types of things are only illtyped when trying to close over a linear variable (variable as in an actual parameter).

**Comment by mdko** [comment]
Wow, thanks for this! I'm glad it's been helpful. I hadn't looked at this in years.

Yes, it looks like you're right. I stepped through that example with Figures 1-5 and 1-6 and saw that I wasn't properly comparing the environments with respect to context difference. It's been fixed.

There are very likely other issues too (for example, I just saw that my parser isn't working for many of the files in `progs/`), but I'll try and fix them and others when I get time.

Thanks again!

**Comment by jjant** [comment]
Oh, great! To be honest I didn't expect you to see it because you hadn't touched this in a while 😄.
I was implementing the language in Elm and your test cases helped greatly (all the typechecker ones had passed except for this one).

Thanks!
